2020-05-13 19:35:27,340 - root - INFO - Started
2020-05-13 19:35:27,345 - root - ERROR - Traceback (most recent call last):
  File "train/train_wsi_on_512x1x1_pretrained.py", line 55, in <module>
    import_module(f'experiments_configs.{exp_subfolder}.{exp_name}')
  File "/home/ruslan/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'experiments_configs.wsi_on_dummy_512x1x1.90ep_adam_exp_with_min'

